### ISSUE TITLE
Fmovies not working

### ISSUE THREAD

**Issue by Shoninzo** [mbebe/blomqvist#1015] opened 2023-11-12 05:26 UTC
The title explains the problem pretty well

**Comment by jferreira93-web** [comment] 2023-11-12 14:31
Fmovies? Right it is, vidplay and mycloud not working, hope it gets fixed soon, it's my go to addon, the best one

**Comment by pitsi** [comment] 2023-11-14 06:46
And here is the error log for vidplay
```
2023-11-14 08:37:34.351 T:140293662156544   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1063: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fmoviesz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2023-11-14 08:37:37.042 T:140293826066560   ERROR: Previous line repeats 1 times.
2023-11-14 08:37:37.042 T:140293826066560 WARNING: CGUIWindowManager - HandleAction - ignoring action 92, because topmost modal dialog closing animation is running
2023-11-14 08:37:37.305 T:140293662156544   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1063: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vidplay.site'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2023-11-14 08:37:37.960 T:140293662156544   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1063: InsecureRequestWarning: Unverified HTTPS request is being made to host '9anime.eltik.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2023-11-14 08:37:38.857 T:140293826066560   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fmoviesto/?moviescount=0&url=2456667%7Chttps%3A%2F%2Ffmoviesz.to%2Fmovie%2Foppenheimer-j2r74&movie=True&image=https%3A%2F%2Fimg.fmoviesz.to%2Fi%2Fcache%2Fimages%2F0%2F04%2F04f7d5c5954f7c9c2e1313e0b34e4306.jpg&title=Oppenheimer+-+%5BI%5D%5BCOLOR+khaki%5DVidplay%5B%2FI%5D++%5BB%5D%5B%2FCOLOR%5D%5B%2FB%5D&mode=playlink&page=1]
```
and the one one for mycloud
```
2023-11-14 08:38:22.815 T:140293662156544   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1063: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fmoviesz.to'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2023-11-14 08:38:25.279 T:140293826066560   ERROR: Previous line repeats 1 times.
2023-11-14 08:38:25.279 T:140293826066560 WARNING: CGUIWindowManager - HandleAction - ignoring action 92, because topmost modal dialog closing animation is running
2023-11-14 08:38:25.543 T:140293662156544   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1063: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vidplay.site'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2023-11-14 08:38:26.050 T:140293662156544   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1063: InsecureRequestWarning: Unverified HTTPS request is being made to host '9anime.eltik.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2023-11-14 08:38:26.524 T:140293826066560   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fmoviesto/?moviescount=0&url=2456666%7Chttps%3A%2F%2Ffmoviesz.to%2Fmovie%2Foppenheimer-j2r74&movie=True&image=https%3A%2F%2Fimg.fmoviesz.to%2Fi%2Fcache%2Fimages%2F0%2F04%2F04f7d5c5954f7c9c2e1313e0b34e4306.jpg&title=Oppenheimer+-+%5BI%5D%5BCOLOR+khaki%5DMyCloud%5B%2FI%5D++%5BB%5D%5B%2FCOLOR%5D%5B%2FB%5D&mode=playlink&page=1]
```
Because that ssl warning worries me a lot, I must add that the above is from kodi 18.9 (libreelec 9.2.x) which has openssl 1.1.1d from 2019. However, it also happens on kodi 19.4 (libreelec 10.0.4).

Last but not least, fbox, whose page seems like an exact clone of fmovies to me, also has the same issue.

**Comment by Shoninzo** [comment] 2023-11-19 05:19
I wonder if they are working on a solution

**Comment by mbebe** [comment] 2023-11-24 19:37
Ok. Both  - fmovies and fbox updated.

**Comment by Shoninzo** [comment] 2023-11-24 21:19
Thanks for your service

**Comment by pitsi** [comment] 2023-11-25 06:33
Still not working on my end with kodi 18. At least this time the error seems to be related to python2's shortcomings (compared to python3).
```
2023-11-25 08:16:57.275 T:140313639491328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0x83 in position 4: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1548, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 1400, in router
                                                PlayLink(exlink)
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 715, in PlayLink
                                                stream_url = decodeVidstream(link2)
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 811, in decodeVidstream
                                                v = encode_id(query[0])
                                              File "/storage/.kodi/addons/plugin.video.fmoviesto/main.py", line 783, in encode_id
                                                cbn = cbn.encode('Latin_1')
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 4: ordinal not in range(128)
                                            -->End of Python script error report<--
2023-11-25 08:16:57.459 T:140315138373760   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.fmoviesto/?moviescount=0&url=2456667%7Chttps%3A%2F%2Ffmoviesz.to%2Fmovie%2Foppenheimer-j2r74&movie=True&image=https%3A%2F%2Fimg.fmoviesz.to%2Fi%2Fcache%2Fimages%2F0%2F04%2F04f7d5c5954f7c9c2e1313e0b34e4306.jpg&title=Oppenheimer+-+%5BI%5D%5BCOLOR+khaki%5DVidplay%5B%2FI%5D++%5BB%5D%5B%2FCOLOR%5D%5B%2FB%5D&mode=playlink&page=1]
```
This is for vidplay, but the same error happens on mycloud too, and on fbox as well. 

As for the why I prefer vidplay or mycloud over filemoon, it is because they both support hls streaming. I have capped the bandwidth kodi can use to 2.5-3Mbps, so any stream that supports hls limits its resolution accordingly. And while vidplay and mycloud limit their resolution to 720p with that cap, filemoon plays 1080p no matter what, which is too much for my hardware and framedrops happen from the first seconds.

On the other hand, it seems to work fine on le 10 with kodi 19, which uses python3. I said "it seems" because it failed once or twice earlier, but played fine later on. On top of that, because the le 10 installation gets its ip and dns via dhcp (the le 9 one has static ip and cloudflare's dns servers), I thought that the error at my previous post may be an indicator that the isp blocks access to those sites.

p.s. I have no problem if you drop support for python2, as long as you do add it in each addon's addon.xml file. That will make them directly incompatible with earlier kodi versions and kodi itself won't even show them as available for install from the repo, i.e. like lookmovie which is only visible to kodi 19 and newer due to python3 (xbmc.python=3.0.0).

**Comment by mbebe** [comment] 2023-11-26 15:24
```
        cbn = dec2(k1,id_)
	try:
		#python 3
		cbn = cbn.encode('Latin_1')
	except:
		#python 2
		cbn = cbn.decode('Latin_1')
		pass
	cbn = dec2(k2,cbn)
	try:
		#python 3
		cbn = cbn.encode('Latin_1')
	except:
		#python 2
		pass
```
and should be ok.

**Comment by pitsi** [comment] 2023-11-26 16:32
It worked!!! Thank you very very much! I can finally watch my series on fmovies again!
Please make a commit for it and include the fix in the next release.

**Comment by pitsi** [comment] 2023-11-28 18:27
@Shoninzo 
You can now close the issue :)

**Closed** 2023-11-28 18:51 UTC

**Comment by pitsi** [comment] 2023-12-07 12:28
I made a small discovery thanks to mpv. Trying to play the stream kodi would play on mpv shows that something on the server's side makes the video stop with a 524 error
```
[ffmpeg] https: HTTP error 524                            
[ffmpeg/demuxer] hls: keepalive request failed for '(long url here)' with error: 'Server returned 5XX Server Error reply' when opening url, retrying with new connection
[ffmpeg] https: HTTP error 524                                              
[ffmpeg/demuxer] hls: Failed to open segment 664 of playlist 1              

[ffmpeg/demuxer] mpegts: Packet corrupt (stream = 0, dts = 179132250).      
[ffmpeg/demuxer] hls: Packet corrupt (stream = 2, dts = 179128500).
```
The 2 last lines I have seperated from the error ones also repeat before the error happens. So yea, something is happenning on the server's side.

In case anyone is interested in the qualities vidplay and mycloud offer via hls, this is what mpv has to say
```
     Video --vid=1 (h264 1920x1080 24.000fps) (4500 kbps)
 (+) Video --vid=2 (h264 1280x720 24.000fps) (1800 kbps)
     Video --vid=3 (h264 640x360 24.000fps) (720 kbps)
```
If the measured bandwith is equal or greater than 4500kbps, 1080p is selected. If it is between 4499 and 1800kbps, 720p is selected and if it is below 1800kbps, 360p is selected.

**Comment by Shoninzo** [comment] 2023-12-10 06:32
It was just working this morning, as soon as I got back home and want to watch a movie, it broke again

**Comment by pitsi** [comment] 2023-12-10 10:29
Since I have no issues for the last 2 days, I will say the obvious: "please post a log". If you can not post a log, instlal the log viewer addon and check yourself what the log says. If you see this line anywhere
`srcs = (json.loads(ff)).get('result',None).get('sources',None)`
it means that fmovies (the addon) failed to decrypt the playable url, so try later and preferebly at the time I mention above.

Having said all that, I can confirm that the freezing issues of the past days, the ones on which mpv reports a 524 error, have stopped in both hosts.

**Comment by mbebe** [comment] 2023-12-14 16:37
Should be ok again.
New version is available in repo.

**Comment by pitsi** [comment] 2023-12-14 18:25
What was wrong with the previous one? :/

**Comment by pitsi** [comment] 2023-12-15 06:19
12 hours later and everything works. I did not test fbox yesterday, so I tested it today and it simply works with all hosts.
If the new url for the keys does solve that "downtime for 20 minutes each hour" issue for vidplay and mycloud, well done to anyone who discovered it! On my end, both urls seem to provide the same keys.

**Comment by pitsi** [comment] 2023-12-21 04:36
The downtime for vidplay and mycloud seems to have increased to "30 minutes each hour" here. Anyone else notice that?
